### ISSUE TITLE
Add mapping for svn:needs-lock property

### ISSUE THREAD

**Issue by bozaro** [bozaro/git-as-svn#64] opened 2014-10-27 09:42 UTC

**Comment by slonopotamus** [comment] 2016-02-21 15:06
Nobody needs this.

**Comment by slonopotamus** [comment] 2019-04-23 14:57
Okay, #219 wants this.

**Comment by slonopotamus** [comment] 2019-05-08 09:29
Duplicate of #229.

**Comment by slonopotamus** [comment] 2019-05-08 09:29
Duplicates #229

**Closed by slonopotamus** 2019-05-08 09:29 UTC
Labels: enhancement
