### ISSUE TITLE
How to use object store for lfs

### ISSUE THREAD

**Issue by icode** [bozaro/git-as-svn#212] opened 2018-11-06 18:16 UTC
Gitlab now use minio object store, how to configure it?

**Comment by slonopotamus** [comment] 2018-11-07 11:52
We have an unresolved bug with GitLab LFS: #175.

**Comment by slonopotamus** [comment] 2019-04-08 15:46
Duplicate of #175

**Closed by slonopotamus** 2019-04-08 15:46 UTC
Labels: bug, gitlab

**Comment by slonopotamus** [comment] 2019-04-09 13:03
I believe this is fixed in git-as-svn 1.8.0 that was just released.
