### ISSUE TITLE
after update for 1.1.5 

### ISSUE THREAD

**Issue by tozor** [bozaro/git-as-svn#142] opened 2017-12-14 15:50 UTC
User password check error:  tozor
java.io.FileNotFoundException: http://localhost:81/api/v3/session
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1890) ~[?:1.8.0_151]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492) ~[?:1.8.0_151]
        at org.gitlab.api.http.GitlabHTTPRequestor.parse(GitlabHTTPRequestor.java:324) ~[java-gitlab-api-1.2.3.jar:?]
        at org.gitlab.api.http.GitlabHTTPRequestor.to(GitlabHTTPRequestor.java:144) ~[java-gitlab-api-1.2.3.jar:?]
        at org.gitlab.api.http.GitlabHTTPRequestor.to(GitlabHTTPRequestor.java:116) ~[java-gitlab-api-1.2.3.jar:?]
        at org.gitlab.api.GitlabAPI.connect(GitlabAPI.java:54) ~[java-gitlab-api-1.2.3.jar:?]
        at svnserver.ext.gitlab.config.GitLabContext.connect(GitLabContext.java:39) ~[git-as-svn.jar:?]
        at svnserver.ext.gitlab.auth.GitLabUserDB.check(GitLabUserDB.java:59) ~[git-as-svn.jar:?]
        at svnserver.auth.PlainAuthenticator.check(PlainAuthenticator.java:54) ~[git-as-svn.jar:?]
        at svnserver.auth.PlainAuthenticator.authenticate(PlainAuthenticator.java:48) ~[git-as-svn.jar:?]
        at svnserver.server.SvnServer.authenticate(SvnServer.java:295) ~[git-as-svn.jar:?]
        at svnserver.server.SessionContext.authenticate(SessionContext.java:78) ~[git-as-svn.jar:?]
        at svnserver.server.SvnServer.serveClient(SvnServer.java:190) ~[git-as-svn.jar:?]
        at svnserver.server.SvnServer.lambda$run$0(SvnServer.java:165) ~[git-as-svn.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by slonopotamus** [comment] 2017-12-16 21:20
Not enough information.

1. What is your gitlab version?
2. What git-as-svn version did you upgrade from?
3. Do you actually have gitlab running on http://localhost:81/?

**Comment by slonopotamus** [comment] 2017-12-16 21:20
Note to myself: according to https://docs.gitlab.com/ce/api/v3_to_v4.html we should actually update to v4 already.

**Comment by slonopotamus** [comment] 2017-12-19 14:01
I this this issue is a duplicate of #154

**Comment by slonopotamus** [comment] 2017-12-19 14:02
this issue is a duplicate of #154

**Comment by slonopotamus** [comment] 2017-12-19 14:02
Duplicate of #154

**Closed by slonopotamus** 2017-12-19 14:02 UTC
